### PR TITLE
update podfile and podspec to support cocoapod 1.0

### PR DESCRIPTION
**Pull request by omerlh**
See hohl/MIHCrypto#40, this solved part of the issues (I still have the non modular errors, but I gave up for now).

### CODE REVIEW

**Comment by omerlh** [comment]
I am not sure why this failed, maybe I should change the xcode version? I am using xcode 8

**Comment by omerlh** [comment]
@hohl, could you help? Look like it is an issue with the latest Cocoapod version. I tried a couple of things:
 - using xcode 7.3 it does not find the pod project (see the linker errors)
 - using xcode 8.1/8.2 image xctool does not run. I think it is because the latest version does [not support build](https://github.com/facebook/xctool/releases) any more (see the release notes for 0.3 version).

Thanks!

**Comment by hohl** [comment]
Thank you for all your effort. However, I can't provide you any solution. Travis-CI does manage running and setting up all that Xcode build/test related stuff itself (besides the `.travis-ci.yml` config file of course). I have no idea why it tries to run "build" on "xctool" when there is no "build" anymore.

**Comment by omerlh** [comment]
Ok, thanks any way. I will try to file an issue on travis ci repo

**Comment by hohl** [comment]
@omerlh: I know you most probably don't care for that pull request anymore after all that years, but with the latest Cocoapods version it seems to work now. So anyhow, thank you for your commitment!

**Comment by omerlh** [comment]
Thank you!

**Pull request merged**
